 - hosts: localhost
   pre_tasks:
     - name: Update Apt and upgrade packages
       become: true
       apt:
         update_cache: true
         upgrade: true
         state: present
   tasks:
     - import_tasks: tasks/zsh.yml
       tags: zsh
     - import_tasks: tasks/brew.yml 
       tags: brew
     - import_tasks: tasks/dotfiles.yml
       tags: dotfiles
     - import_tasks: tasks/conda.yml
       tags: conda
     - import_tasks: tasks/rust.yml
       tags: rust
     - import_tasks: tasks/node.yml 
       tags: node
