 - hosts: localhost
   pre_tasks:
     - name: Update Apt and upgrade packages
       become: true
       apt:
         update_cache: true
         upgrade: true
         state: present
   tasks:
     - import_tasks: tasks/git.yml
       tags: git
     - import_tasks: tasks/node.yml 
       tags: node
     - import_tasks: tasks/nvim.yml
       tags: nvim
     - import_tasks: tasks/conda.yml
       tags: conda
     - import_tasks: tasks/tmux.yml
       tags: tmux
     - import_tasks: tasks/direnv.yml
       tags: direnv
     - import_tasks: tasks/rust.yml
       tags: rust
     - import_tasks: tasks/dotfiles.yml
       tags: dotfiles
