- name: Remove Previous Miniconda
  file:
    path: ~/miniconda
    state: absent
- name: Download Miniconda
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/miniconda.sh
- name: Install Miniconda
  shell: bash /tmp/miniconda.sh -b -p ~/miniconda
