- name: Create Miniconda directory
  file:
    path: ~/miniconda3
    state: directory
- name: Download Miniconda installer script
  shell: bash smart_download_conda.sh
- name: Install Miniconda
  shell: bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
- name: Remove Miniconda installer script
  file:
    path: ~/miniconda3/miniconda.sh
    state: absent
- name: Initialize Conda for Zsh
  shell: ~/miniconda3/bin/conda init zsh
